### ISSUE TITLE
skos-xl conversion problem

### ISSUE THREAD

**Issue by nadjet** [sparna-git/skos-play#2]
Great tool! I just came across a problem with skos-xl conversion.
Say I have a form F for concept C, which acts as preferred label in one language L1 and alternate label in another language L2.
Output of skos-xl conversion is that we have one label with 2 literal forms (one for L1 and one for L2), which is both C's preferred and alternate label.

**Comment by tfrancart** [comment]
Hello

Can you share your source file and the output you get ?
If I understand your situation correctly, this is a corner case; f a form happens to be the same in 2 languages (e.g. "source" in English and "source" in French), 2 skos-xl terms have to be declared, each with a different language, and each having its own relation with the concept (one being preferred, the other being alternate).

**Comment by nadjet** [comment]
Here is an example:

[Archive.zip](https://github.com/sparna-git/skos-play/files/3013793/Archive.zip)

**Comment by tfrancart** [comment]
Great thanks.
Indeed, a bug.
This is now fixed, here is the conversion result of your file :

```
location:test a skos:Concept;
  skos:inScheme <http://neuralalpha.com/vocabularies/location>;
  skos:topConceptOf <http://neuralalpha.com/vocabularies/location>;
  skosxl:altLabel location:test-label-en-1, location:test-label-fr-0;
  skosxl:prefLabel location:test-label-en-0, location:test-label-fr-1 .

location:test-label-fr-0 a skosxl:Label;
  skosxl:literalForm "test"@fr .

location:test-label-en-0 a skosxl:Label;
  skosxl:literalForm "test"@en .

location:test-label-en-1 a skosxl:Label;
  skosxl:literalForm "test1"@en .

location:test-label-fr-1 a skosxl:Label;
  skosxl:literalForm "test2"@fr .
```
