### ISSUE TITLE
New release (war file)

### ISSUE THREAD

**Issue by warenhaus** [sparna-git/skos-play#28]
Hi! It would be great if you can create a new release / war file. the ones availabke under https://bitbucket.org/tfrancart/sparna/downloads/ seem to be outdated. (and I'm not skilled enough to build one myself)

also, can you elaborate on the compatibility with newer versions of java and tomcat?

thank you!

**Comment by tfrancart** [comment]
https://bitbucket.org/tfrancart/sparna/downloads/ is certainly outdated but have you looked under https://github.com/sparna-git/skos-play/releases ? the last release is from october 2019.
There should not be any problems with newer version of Java or Tomcat (to my knowledge).

**Comment by tfrancart** [comment]
Note : I have updated the [Install wiki page](https://github.com/sparna-git/skos-play/wiki/HowTo-SKOSPlayOnTomcat) to have links pointing to Github releases instead of Bitbucket.
