### ISSUE TITLE
CLI version of skos-play

### ISSUE THREAD

**Issue by niva83** [sparna-git/skos-play#39]
[Wiki](https://github.com/sparna-git/skos-play/wiki/HowTo-RunSKOSPlayCommandLine) documents the use-case of the SKOS Play from the command line. 

Wiki points to download `skos-play-cli-x.y.z-onejar.jar` form [download section](https://github.com/sparna-git/skos-play/releases), however, I am not able to find any `.jar` file.

@tfrancart can you point me where I can find a `.jar` file of SKOS Play.

**Comment by niva83** [comment]
@tfrancart found it, there are under older versions of SKOS PLAY!

**Comment by tfrancart** [comment]
Latest release 0.8.8 just published contains the CLI version of SKOS Play!
Thanks
