### ISSUE TITLE
Property value bug with dct:source, incorrect RDF output

### ISSUE THREAD

**Issue by edmondchuc** [sparna-git/skos-play#5]
A column header like:

**dct:source@en** 

with a value:

 *Neldner, V.J., Wilson, B.A., Dillewaard, H.A., Ryan, T.S., Butler, D.W., McDonald, W.J.F, Addicott,E.P. and Appelman, C.N. (2019) Methodology for survey and mapping of regional ecosystems and vegetation communities in Queensland. Version 5.0. Updated March 2019. Queensland Herbarium, Queensland Department of Environment and Science, Brisbane. Table 28.* 

is producing the output

```
<http://linked.data.gov.au/def/corveg-cv/structural-growth-form/418bbf63-40ba-4b31-84d0-6fbf40d690c0> a skos:Concept;
  dct:source "Addicott"@en, "B.A."@en, "Brisbane. Table 28."@en, "Butler"@en, "C.N. (2019) Methodology for survey and mapping of regional ecosystems and vegetation communities in Queensland. Version 5.0. Updated March 2019. Queensland Herbarium"@en,
    "D.W."@en, "Dillewaard"@en, "E.P. and Appelman"@en, "H.A."@en, "McDonald"@en, "Neldner"@en,
    "Queensland Department of Environment and Science"@en, "Ryan"@en, "T.S."@en, "V.J."@en,
    "W.J.F"@en, "Wilson"@en;
```

I **did not** explicitly put the column header like **dct:source@en(separator=",")** but it is still separating the value. 

I tested this with the column header 

**skos:definition** 

and it produces the result as expected

```
<http://linked.data.gov.au/def/corveg-cv/structural-growth-form/418bbf63-40ba-4b31-84d0-6fbf40d690c0> a skos:Concept;
  skos:definition "Neldner, V.J., Wilson, B.A., Dillewaard, H.A., Ryan, T.S., Butler, D.W., McDonald, W.J.F, Addicott,E.P. and Appelman, C.N. (2019) Methodology for survey and mapping of regional ecosystems and vegetation communities in Queensland. Version 5.0. Updated March 2019. Queensland Herbarium, Queensland Department of Environment and Science, Brisbane. Table 28."@en;
```

Therefore, I suspect there is a bug with the tool in processing dct properties like **source**. 

*Note: This bug occurs at the concept scheme as well as the concept level.*

Here is the download link the [Excel file](http://s000.tinyupload.com/index.php?file_id=10959271639960379897).

**Comment by tfrancart** [comment]
Thanks for reporting. Yes this is part of some hardcoded rules for some properties, including dct:source, which remain here for backward compatibility. This is why it happens for dct:source and not dct:description. This should disappear in the future. For now can you try specifying a different separator (like `(separator="###")` ) or you could also try declaring a different prefix for dct in your header (like "dcterms" instead of "dct"), and adjust the header accordingly (dcterms:source instead of dct:source), and I think this should work around this hardcoded rule. Let me know.

**Comment by edmondchuc** [comment]
Hi @tfrancart,

Thanks a lot for your prompt response. Your suggestion of using the prefix **dcterms** instead of **dct** fixed the problem.

Cheers.
