### ISSUE TITLE
Google login failing

### ISSUE THREAD

**Issue by dr-shorthair** [sparna-git/skos-play#56]
![image](https://user-images.githubusercontent.com/608303/123910691-2acca380-d9be-11eb-9ebf-4a4163406a10.png)

**Comment by tfrancart** [comment]
Ha yes, this has not been maintained for a long time. Your best bet for now is to download an Excel version of your Google Spreadsheet, then upload it in SKOS Play.

Alternatively, you could:
1. Share your spreadsheet with "Everyone with the link"
2. Build the Excel URL of your spreadhseet, which is: https://docs.google.com/spreadsheets/d/<ID of your spreadhseet>/export?format=xlsx 
3. Submit that URL to SKOS Play in the third field of the form

**Comment by dr-shorthair** [comment]
Yeah - that is what I have been doing until now. I was introducing SKOS Play to some new users and checking out all the options. Maybe remove the Google options from the UI?

**Comment by graybeal** [comment]
I also suggest removing the spreadsheet option, replacing it with the workaround instructions you provide above. It's a wonderful workaround, obvious only once you know it. :-)

**Comment by tfrancart** [comment]
Hello, as suggested, I removed the option from the UI and replaced it with a help text : https://skos-play.sparna.fr/play/convert.
Please close the issue if happy.

**Comment by dr-shorthair** [comment]
Thx @tfrancart
