### ISSUE TITLE
Suggestion dans l'option "In a local file on my computer"

### ISSUE THREAD

**Issue by quidoz** [sparna-git/skos-play#6]
Bonjour

J’ai voulu tester skos-play http://labs.sparna.fr/skos-play/upload sur le thesaurus de la biodiversité (loterre). 

SI je mets l’URL https://www.loterre.fr/wp-content/uploads/2019/02/Biodiversit%C3%A9_SKOS.xml c’est OK. 

Si je mets le fichier sauvegardé (Biodiversité_SKOS.xml ) ;, ça me dit 
Erreur
Aucun concept SKOS n'a pu être trouvé dans les données. Cette application ne peut traiter que des données SKOS.

Le problème vient du fait que le fichier en xml n'est pas supporté (alors qu’il l'est pour les URL)

Ca serait peut être bien de le mettre dans la doc (Extensions supportées : .rdf, .ttl, .n3, .trig, .zip, .tar.gz. Les autres extensions seront considérées comme du RDF/XML)

MCQ

**Comment by tfrancart** [comment]
Bonjour et merci pour le feedback.

Le format RDF utilisé pour le parsing est déterminé de façon différente dans les 2 cas : dans le cas d'un chargement par l'URL c'est le _Content-Type_ de la réponse du serveur qui est utilisé pour déterminer le format. Dans le cas d'un chargement par fichier, c'est l' _extension_ du fichier qui est utilisée.
Il se trouve que l'extension *.xml est associée au format [TrIX](https://en.wikipedia.org/wiki/TriX_(serialization_format)), et pas au format RDF/XML; j'avais changé ça initialement dans SKOS Play pour que l'extension *.xml soit associé à du RDF/XML car c'est le cas le plus courant, mais je pense que cette customisation a du sautée au moment de la migration vers RDF4J. Il faut que je regarde dans le détail.

**Comment by tfrancart** [comment]
En attendant, il vous suffit de renommer votre fichier avec une extension *.rdf à la place de *.xml pour qu'il soit interprété correctement (ce qui serait de toute façon une bonne chose à faire dans l'absolu)
