### ISSUE TITLE
How to specify a typed literal in the header?

### ISSUE THREAD

**Issue by EmidioStani** [sparna-git/skos-play#75]
In the header of the spreadsheet if I specify:

dct:created	"2018-07-09"^^xsd:date

the generated RDF becomes a literal surrounding the xsd:date, e.g:

dct:created "\"2018-07-09\"^^xsd:date";

or if I remove the double quotes:

dct:created	2018-07-09^^xsd:date

it becomes:

dct:created "2018-07-09^^xsd:date";

**Comment by tfrancart** [comment]
No no, you need to specify the datatype on the property header, not in the value cell. Like so:

![image](https://user-images.githubusercontent.com/2728945/205923158-0e5979ba-4002-4c13-b198-d3f0a5e8f7ec.png)

This is the same syntax as documented at https://skos-play.sparna.fr/play/convert#datatypes
