### ISSUE TITLE
Error: unqualified attribute 'Extension' not allowed [line 2, column 193] in [Content_Types].xml [line 2, column 193]

### ISSUE THREAD

**Issue by LongJenny** [sparna-git/skos-play#80]
I'm trying to convert a new vocabulary from Excel to RDF using a template I created based on SKOS-Play! recommendations.  It's an extremely simple vocabulary for testing purposes (only URI, prefLabel, definition and altLabel, with no content in altLabel).  Every time I try to run it I get the following:
![image](https://user-images.githubusercontent.com/74519443/221061988-02dc47ad-52b1-4dce-b596-8adf9d843682.png)

I haven't used this template for over a year, but last time I was able to successfully convert using SKOS-Play!  I've checked and re-checked my document and can't see any errors.  Following is a screenshot of the template: 
![image](https://user-images.githubusercontent.com/74519443/221067700-31c0df0f-6d69-4a51-9350-7f3c6f230d1a.png)

Is it possible this error isn't to do with my template, but something in the code?

**Comment by tfrancart** [comment]
I think you're mixing SKOS Play reporting feature with SKOS Play conversion feature. Are you sure you upload you Excel file in the **conversion** form at https://skos-play.sparna.fr/play/convert and **not** in the reporting form at https://skos-play.sparna.fr/play/upload ?
The Excel file must first be converted into SKOS, and then you can generate reports from the RDF/SKOS file.

Please share your Excel file if problem persists.

**Comment by LongJenny** [comment]
Thank you - yes, you are correct.  File is converting successfully, and I am feeling embarrassed but pleased
