### ISSUE TITLE
Error 500 when uploading file or using one of the examples

### ISSUE THREAD

**Issue by EmidioStani** [sparna-git/skos-play#85]
Hello @tfrancart ,

I am getting error 500 either when I upload a file or using one of those examples, with the message:

 Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. No space left on device

Best,

Emidio

**Comment by tfrancart** [comment]
Server is up again, thank you
